"""
Django settings for BeautyVibe project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--@0x=o-*bc%_ru-67eg3srhe!3-878cjjz-%6s==00=r!g(eu4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # frameworks
    'rest_framework',
    'rest_framework.authtoken',
    #local apps
    'UserAuthentication',
    'Products',
    'UserProfile',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'BeautyVibe.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'BeautyVibe.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]




# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# REST_FRAMEWORK ={
#     'DEFAULT_AUTHENTICATION_CLASSES':[
#         "rest_framework_simplejwt.authentication.JWTAuthentication",
        
#     ],
#     "EXCEPTION_HANDLER": "core.exceptions.error"
# }


# Allow all origins for CORS (including any device on the same WiFi network)
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# CSRF configuration for external access
CSRF_TRUSTED_ORIGINS = [
    "http://10.10.12.62:8000",
    "http://10.10.12.59:3000",
    "http://127.0.0.1:8000",
    "http://localhost:8002",
    "http://10.10.12.11:3000",
]


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    
}

from datetime import timedelta
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),

    "AUTH_HEADER_TYPES": ("Bearer",),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": True,
}

AUTH_USER_MODEL = "UserAuthentication.User"

# Use your email provider credentials here
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'              
EMAIL_USE_TLS = True                        
EMAIL_PORT = 587
EMAIL_HOST_USER = 'mahedi.dev2002@gmail.com'  
EMAIL_HOST_PASSWORD = 'dnsa iihv qpda pzpy'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# Google Authentication
GOOGLE_CLIENT_ID = "620271018280-r59n2ut8jtl6v7noqlboaj5l6tgbn8ja.apps.googleusercontent.com"
Client_secret="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"
import stripe

from django.conf import settings

STRIPE_SECRET_KEY = "sk_test_51T3TvU3k43qHJ6v15scxDJrVfx9yfHPG3jYxREZuViB3eBFmXjAc9K1bhYewybJgTkRYkCBsxv1hwvLu4EwRpjZH00EQBHSNNb"
STRIPE_PUBLISHABLE_KEY = "pk_test_51T3TvU3k43qHJ6v1raNTc4xEW9E8ZZ3ZCGkDCk3UQuccmtOA2gLV3s17Ipfq1SEYi9N5XAPVtmCasAeI2Xf0vQvx00Os5PwqcL"
STRIPE_WEBHOOK_SECRET = "whsec_d8955f155f40d295efaad8c62c022ee0142299b2ee5dd886e179768ab577c03a"

stripe.api_key = settings.STRIPE_SECRET_KEY


AI_API_URL ="https://wbsl64n9-8004.inc1.devtunnels.ms"

COMMISSION_RATE= 0.10