# Generated by Django 6.0.2 on 2026-03-02 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Full_name',
            new_name='full_name',
        ),
    ]
