# Generated by Django 6.0.2 on 2026-03-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
