# Generated by Django 6.0.2 on 2026-03-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0009_sharedvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='payment_method',
            field=models.CharField(default='Stripe', max_length=100),
        ),
    ]
