# Generated by Django 6.0.2 on 2026-03-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_order_is_paid_order_stripe_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.FileField(blank=True, null=True, upload_to='product_videos/'),
        ),
    ]
