# Generated by Django 6.0.2 on 2026-03-04 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_alter_product_category'),
        ('UserProfile', '0002_alter_video_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_cart_items', to='UserProfile.video'),
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
