# Generated by Django 6.0.2 on 2026-03-07 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0013_orderhistory'),
        ('UserProfile', '0005_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items_video', to='UserProfile.video'),
        ),
    ]
