# Generated by Django 6.0.2 on 2026-03-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0016_alter_paymenthistory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_id',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
