# Generated by Django 6.0.2 on 2026-03-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0017_alter_paymenthistory_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
