# Generated by Django 6.0.2 on 2026-03-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0019_creatorwithdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorwithdrawal',
            name='withdraw_method',
            field=models.CharField(choices=[('bank_account', 'Bank Account'), ('debit_card', 'Debit Card'), ('unknown', 'Unknown')], default='unknown', max_length=30),
        ),
    ]
