# Generated by Django 6.0.2 on 2026-03-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0020_creatorwithdrawal_withdraw_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorwithdrawal',
            name='bank_last4',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='creatorwithdrawal',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
